---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: informix-anyuid-role
rules:
  - apiGroups:
    - security.openshift.io
    resourceNames:
      - anyuid
    resources:
      - securitycontextconstraints
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: informix-anyuid-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: informix-anyuid-role
subjects:
  - kind: ServiceAccount
    name: informix-sa