apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: informix-persistent
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: informix-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: informix-config
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: informix-tmpfile
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  status: {}
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: informix
    name: informix
  spec:
    replicas: 1
    selector:
      app: informix
      deploymentconfig: informix
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          app: informix
          deploymentconfig: informix
      spec:
        containers:
        - name: informix
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
            - containerPort: 9088
              protocol: TCP
            - containerPort: 9091
              protocol: TCP
            - containerPort: 27018
              protocol: TCP
            - containerPort: 27883
              protocol: TCP
            - containerPort: 9089
              protocol: TCP
            - containerPort: 9090
              protocol: TCP
            - containerPort: 9092
              protocol: TCP
          resources:
            limits:
              memory: 8Gi
            requests:
              memory: 1Gi
          securityContext: {}
          env:
            - name: TZ
              value: 'Asia/Taipei'
            - name: LICENSE
              value: accept
            - name: STORAGE
              value: local
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File          
          volumeMounts:
            - name: informix-localdata
              mountPath: /opt/ibm/data
            - name: informix-config
              mountPath: /opt/ibm/config
            - name: informix-tmpfile
              mountPath: /opt/ibm/files 
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
          fsGroup: 54321
        serviceAccount: informix-sa
        serviceAccountName: informix-sa
        terminationGracePeriodSeconds: 30
        volumes: 
        - name: informix-localdata
          persistentVolumeClaim:
            claimName: informix-data 
        - name: informix-tmpfile
          persistentVolumeClaim:
            claimName: informix-tmpfile
        - name: informix-config
          persistentVolumeClaim:
            claimName: informix-config    
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - informix
        from:
          kind: ImageStreamTag
          name: informix-innovator-c:14.10.FC7W1IE
      type: ImageChange
    - type: ConfigChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: informix
    name: informix
  spec:
    ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: 9088-tcp
      protocol: TCP
      port: 9088
      targetPort: 9088
    - name: 9089-tcp
      protocol: TCP
      port: 9089
      targetPort: 9089
    - name: 9090-tcp
      protocol: TCP
      port: 9090
      targetPort: 9090
    - name: 9091-tcp
      protocol: TCP
      port: 9091
      targetPort: 9091
    - name: 9092-tcp
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name: 27017-tcp
      protocol: TCP
      port: 27017
      targetPort: 27017
    - name: 27018-tcp
      protocol: TCP
      port: 27018
      targetPort: 27018
    - name: 27883-tcp
      protocol: TCP
      port: 27883
      targetPort: 27883 
    selector:
      deploymentconfig: informix
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
