kind: Deployment
apiVersion: apps/v1
metadata:
  name: informix
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: informix
  template:
    metadata:
      labels:
        deployment: informix
    spec:
      volumes:
        - name: informix-volume-3
          emptyDir: {}
        - name: informix-volume-2
          persistentVolumeClaim:
            claimName: informix
        - name: informix-volume-5
          configMap:
            name: informix-surrogates
            defaultMode: 420
        - name: informix-1
          configMap:
            name: informix-conf
            defaultMode: 420
        - name: informix-volume-1
          configMap:
            name: informix-conf
            defaultMode: 420
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: informix
          ports:
            - containerPort: 27017
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
            - containerPort: 9088
              protocol: TCP
            - containerPort: 9091
              protocol: TCP
            - containerPort: 27018
              protocol: TCP
            - containerPort: 27883
              protocol: TCP
            - containerPort: 9089
              protocol: TCP
            - containerPort: 9090
              protocol: TCP
            - containerPort: 9092
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: informix-volume-1
              mountPath: /opt/ibm/config/onconfig
              subPath: onconfig
            - name: informix-volume-2
              mountPath: /opt/ibm/data
            - name: informix-volume-3
              mountPath: /opt/ibm/files
            - name: informix-volume-5
              mountPath: /etc/informix/allowed.surrogates
              subPath: allowed.surrogates
          terminationMessagePolicy: File
          envFrom:
            - configMapRef:
                name: informix-env
          image: >-
            ibmcom/informix-innovator-c:14.10.FC7W1IE
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext:
        runAsUser: 200
      schedulerName: default-scheduler 
---
kind: Service
apiVersion: v1
metadata:
  name: informix
  labels:
    app: informix
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: 9088-tcp
      protocol: TCP
      port: 9088
      targetPort: 9088
    - name: 9089-tcp
      protocol: TCP
      port: 9089
      targetPort: 9089
    - name: 9090-tcp
      protocol: TCP
      port: 9090
      targetPort: 9090
    - name: 9091-tcp
      protocol: TCP
      port: 9091
      targetPort: 9091
    - name: 9092-tcp
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name: 27017-tcp
      protocol: TCP
      port: 27017
      targetPort: 27017
    - name: 27018-tcp
      protocol: TCP
      port: 27018
      targetPort: 27018
    - name: 27883-tcp
      protocol: TCP
      port: 27883
      targetPort: 27883
  internalTrafficPolicy: Cluster
  clusterIPs:
    - 172.30.145.179
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    deployment: informix
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: informix
  namespace: informix
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: informix-env
data:
  DBA_PASSWORD: test
  DBA_USER: test
  DEBUG: 'on'
  LICENSE: accept
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: informix-sqlhosts
data:
  sqlhosts: "############################################################\r\n### DO NOT MODIFY THIS COMMENT SECTION \r\n### HOST NAME = 8c2adabc68ef \r\n############################################################\r\njoe             onsoctcp        *                     9088\r\ninformix        onsoctcp        *8c2adabc68ef         9088\r\ninformix_dr     drsoctcp        *8c2adabc68ef         9089:"

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: informix-conf
  namespace: informix
data:
  onconfig: "#################\n#\n# Licensed Material - Property of IBM and/or HCL\n#\n# Informix Dynamic Server\n# Copyright IBM Corporation 1996, 2017. All rights reserved.\n# (c) Copyright HCL Technologies Ltd. 2017, 2022. All Rights Reserved.\n#\n# Title: onconfig.std\n# Description: Informix Dynamic Server Configuration Parameters\n#\n# Important: $INFORMIXDIR now resolves to the environment\n# variable INFORMIXDIR. Replace the value of the INFORMIXDIR\n# environment variable only if the path you want is not under\n# $INFORMIXDIR.\n#\n# For additional information on the parameters:\n# https://www.ibm.com/support/knowledgecenter/SSGU8G/welcomeIfxServers.html\n#\n###################################################################\n\n###################################################################\n# Root Dbspace Configuration Parameters\n###################################################################\n# ROOTNAME     - The name of the root dbspace, which contains reserved \n#                pages and internal tracking tables.\n# ROOTPATH     - The path for the device containing the root chunk\n# ROOTOFFSET   - The starting offset, in KB, of the primary root chunk.\n#                An offset is required for some raw devices.\n# ROOTSIZE     - The size of the root chunk, in KB.  The value of\n#                300000 allows for a default user space of about\n#                180 MB and the default system space requirements.\n# MIRRORPATH   - The path for the device containing the root chunk's\n#                mirror (optional)\n# MIRROROFFSET - The starting offset, in KB, of the root chunk's mirror\n#\n# Warning: Always verify ROOTPATH/ROOTOFFSET before performing\n#          disk initialization (oninit -i or -iy) to avoid disk\n#          corruption of another instance\n###################################################################\n\nROOTNAME rootdbs\nROOTPATH /opt/ibm/data/spaces/rootdbs.000\nROOTOFFSET 0\nROOTSIZE 350000\nMIRRORPATH\nMIRROROFFSET 0\n\n###################################################################\n# Physical Log Configuration Parameters\n###################################################################\n# PHYSFILE           - The size, in KB, of the physical log on disk.\n#                      If RTO_SERVER_RESTART is enabled, the\n#                      suggested formula for the size of PHSYFILE\n#                      (up to about 1 GB) is:\n#                          PHYSFILE = Size of BUFFERS * 1.1\n# PLOG_OVERFLOW_PATH - The directory for extra physical log data\n#                      if the physical log overflows during recovery\n#                      or long transaction rollback\n# PHYSBUFF           - The size of the physical log buffer, in KB\n###################################################################\n\nPHYSFILE 50000\nPLOG_OVERFLOW_PATH  $INFORMIXDIR/tmp\nPHYSBUFF 128\n\n###################################################################\n# Logical Log Configuration Parameters\n###################################################################\n# LOGFILES     - The number of logical log files\n# LOGSIZE      - The size of each logical log, in KB\n# DYNAMIC_LOGS - The type of dynamic log allocation.\n#                Acceptable values are:\n#                2 Automatic. The server adds a new logical log when\n#                  necessary.\n#                1 Manual. The server notifies the DBA to add new logical\n#                  logs when necessary.\n#                0 Disabled\n# LOGBUFF      - The size of the logical log buffer, in KB\n# AUTO_LLOG    - Add logical logs automatically to improve performance\n###################################################################\n\nLOGFILES 10\nLOGSIZE 10000\nDYNAMIC_LOGS 2\nLOGBUFF 128\n\n###################################################################\n# Long Transaction Configuration Parameters\n###################################################################\n# If the server cannot roll back a long transaction, the server hangs\n# until more disk space is available.\n#\n# LTXHWM       - The percentage of the logical logs that can be\n#                filled before a transaction is determined to be a\n#                long transaction and is rolled back\n# LTXEHWM      - The percentage of the logical logs that have been\n#                filled before the server suspends all other\n#                transactions so that the long transaction being\n#                rolled back has exclusive use of the logs\n#\n# When dynamic logging is on, you can set higher values for\n# LTXHWM and LTXEHWM because the server can add new logical logs\n# during long transaction rollback. Set lower values to limit the\n# number of new logical logs added.\n#\n# If dynamic logging is off, set LTXHWM and LTXEHWM to\n# lower values, such as 50 and 60 or lower, to prevent long\n# transaction rollback from hanging the server due to lack of\n# logical log space.\n#\n# When using Enterprise Replication, set LTXEHWM to at least 30%\n# higher than LTXHWM to minimize log overruns.\n###################################################################\n\nLTXHWM 70\nLTXEHWM 80\n\n###################################################################\n# Server Message File Configuration Parameters\n###################################################################\n# MSGPATH      - The path of the server message log file\n# MSG_DATE     - Customize the date or time preceding each message written\n#                to MSGPATH. MSG_DATE values result in these formats:\n#    0           HH:MM:SS\n#    1           MM/DD/YYYY HH:MM:SS (Locale-dependent ordering of MM and DD)\n#    2           Milliseconds since epoch + MM/DD/YYYY HH:MM:SS (Locale-\n#                dependent ordering of MM and DD)\n#    3           YYYY-MM-DD HH:MM:SS.FFF\n# CONSOLE      - The path of the server console message file\n###################################################################\n\nMSGPATH /opt/ibm/data/logs/online.log\nMSG_DATE    3\nCONSOLE /opt/ibm/data/logs/console.log\n\n###################################################################\n# Tblspace Configuration Parameters\n###################################################################\n# TBLTBLFIRST    - The first extent size, in KB, for the tblspace\n#                  tblspace. Must be in multiples of the page size.\n# TBLTBLNEXT     - The next extent size, in KB, for the tblspace\n#                  tblspace. Must be in multiples of the page size.\n# The default setting for both is 0, which allows the server to manage\n# extent sizes automatically.\n#\n# TBLSPACE_STATS - Enables (1) or disables (0) the server to maintain\n#                  tblspace statistics\n###################################################################\n\nTBLTBLFIRST 0\nTBLTBLNEXT 0\nTBLSPACE_STATS 1\n\n###################################################################\n# Temporary dbspace and sbspace Configuration Parameters\n###################################################################\n# DBSPACETEMP  - The list of dbspaces used to store temporary\n#                tables and other objects. Specify a colon\n#                separated list of dbspaces that exist when the\n#                server is started. If no dbspaces are specified,\n#                or if all specified dbspaces  are not valid,\n#                temporary files are created in the /tmp directory\n#                instead.\n# SBSPACETEMP  - The list of sbspaces used to store temporary\n#                tables for smart large objects. If no sbspace\n#                is specified, temporary files are created in\n#                a standard sbspace.\n###################################################################\n\nDBSPACETEMP\nSBSPACETEMP\n\n###################################################################\n# Dbspace and sbspace Configuration Parameters\n###################################################################\n# SBSPACENAME    - The default sbspace name where smart large objects\n#                  are stored if no sbspace is specified during\n#                  smart large object creation. Some DataBlade\n#                  modules store smart large objects in this\n#                  location.\n# SYSSBSPACENAME - The default sbspace for system statistics\n#                  collection. Otherwise, the server stores statistics\n#                  in the sysdistrib system catalog table.\n# ONDBSPACEDOWN  - Specifies how the server behaves when it encounters a\n#                  dbspace that is offline. Acceptable values\n#                  are:\n#                  0 Continue\n#                  1 Stop\n#                  2 Wait for DBA action\n###################################################################\n\nSBSPACENAME sbspace\nSYSSBSPACENAME\nONDBSPACEDOWN 2\n\n\n###################################################################\n# System Configuration Parameters\n###################################################################\n# SERVERNUM       - The unique ID for the server instance. Acceptable\n#                   values are 0 through 255, inclusive.\n# DBSERVERNAME    - The name of the default database server\n# DBSERVERALIASES - The list of up to 32 alternative dbservernames,\n#                   separated by commas\n# FULL_DISK_INIT  - Specifies if oninit -i can run:\n#                   0 allows full disk initialization only if no\n#                     instance is detected at the rootchunk location.\n#                     For oninit -ie allows full disk initialization\n#                     only if no existing encryption key database or\n#                     stashfile are found.\n#                   1 required if an existing instance is detected at\n#                     the rootchunk location.  For oninit -ie,\n#                     required if an existing encryption key database\n#    or stashfile is found. "

